export const syllabus = [
  {
    title: "10th Kyu",
    subtitle: "Taikyoku Shodan",
    left: "<h4>SUBJECTS</h4><h5>Basic Punches<br />Middle punch - Chudan Zuki<br />Face punch - Jodan Zuki <br />Down punch - Gedan Zuki<br />Blocks :<br />Down Block - Gedan Uke<br />Upper block - Jodan Uke<br />Inner forearm block - Uchi Ude Uke<br />Outer forearm block - Soto Ude Uke</h5>",
    right:
      "<h5>Stance :<br />Horse Stance - Kiba Dachi<br />Forward Stance - Zenkutsu Dachi<br />Kicks :<br />Front Kick - Mae Geri.</h5><h4>BELT TECHNIQUES</h4>",
    imgUrl: "/images/syllabus/kyu-10.png",
  },
  {
    title: "9th Kyu",
    subtitle: "Taikyoku Sandan",
    left: "<h4>SUBJECTS</h4><h5>6 Punches<br />Combination of Basic Punches and Blocks<br />Kicks:<br />Side Kick - Yuko Geri<br />Stance:<br />Back Stance - Kokustu Dachi</h5>",
    right: "<h4>BELT TECHNIQUES</h4>",
    imgUrl: "/images/syllabus/kyu-9.png",
  },
  {
    title: "8th Kyu",
    subtitle: "Hein Shodan",
    left: "<h4>SUBJECTS</h4><h5>Block Combination<br />Back Fist Strike - Uraken Uchi<br />Chopping Technique - Shuto Uchi<br />Kicks:<br />Slap Kick - Mawashi Geri<br />Knife hand Block - Shuto Uke</h5>",
    right: "<h4>BELT TECHNIQUES</h4>",
    imgUrl: "/images/syllabus/kyu-8.png",
  },
  {
    title: "7th Kyu",
    subtitle: "Hein Nidan",
    left: "<h4>SUBJECTS</h4><h5>Combination of Blocks, Punches and Back Fists techniques.<br/>Elbow Strikes - Empi Uchi.<br/>Kicks:<br/>Back Kick - Oshiro Geri</h5>",
    right: "<h4>BELT TECHNIQUES</h4>",
    imgUrl: "/images/syllabus/kyu-7.png",
  },
  {
    title: "6th Kyu",
    subtitle: "Hein Sandan",
    left: "<h4>SUBJECTS</h4><h5>Combinations of Blocks, Punches, Elbow Strikes and Back Fisttechniques.<br />Kicks:<br />Inner Crescent Kick - Soto Mikazuki Geri<br />Outer Crescent Kick - Uchi Mikazuki Geri<br />Front Back Kick - Mae Oshiro Geri<br />Foot Sweeps - Ashi Barai</h5>",
    right: "<h4>BELT TECHNIQUES</h4>",
    imgUrl: "/images/syllabus/kyu-6.png",
  },
  {
    title: "5th Kyu",
    subtitle: "Hein Yondan",
    left: "<h4>SUBJECTS</h4><h5>Stance:<br/>Cat Stance - Neko Ashi Dachi<br/>Kicks:<br/>Turning Kick - Mawashi Geri<br/>Hook Kick - Kake Geri / Ura Mawashi Geri<br/>Spinning Kicks -  Oshiro Mawashi Geri</h5>",
    right: "<h4>BELT TECHNIQUES</h4>",
    imgUrl: "/images/syllabus/kyu-5.png",
  },
  {
    title: "4th Kyu",
    subtitle: "Hein Godan",
    left: "<h4>SUBJECTS</h4><h5>Kicks:<br/>Jumping Front Kick<br/>Jumping Side Kick</h5>",
    right: "<h4>BELT TECHNIQUES</h4>",
    imgUrl: "/images/syllabus/kyu-4.png",
  },
  {
    title: "3rd Kyu",
    subtitle: "Tekki Shodan",
    left: "<h4>SUBJECTS</h4><h5>Double Jumping Front Kick<br/>Double Jumping Side Kick</h5>",
    right: "<h4>BELT TECHNIQUES</h4>",
    imgUrl: "/images/syllabus/kyu-3.png",
  },
  {
    title: "2nd Kyu",
    subtitle: "Tekki Nidan",
    left: "<h4>SUBJECTS</h4><h5>Front leg Jumping Front Kick<br/>Front leg Jumping Side Kick<br/>Take downs</h5>",
    right: "<h4>BELT TECHNIQUES</h4>",
    imgUrl: "/images/syllabus/kyu-2.png",
  },
  {
    title: "1st Kyu",
    subtitle: "Tekki Sanda & Bassadal",
    left: "<h4>SUBJECTS</h4><h5>Throws<br/>Flying Kicks</h5>",
    right: "<h4>BELT TECHNIQUES</h4>",
    imgUrl: "/images/syllabus/kyu-1.png",
  },
];

export const jpList = [
  {
    title: "Sharan N",
    subtitle: "Manager Kumite Coach",
    imgUrl: "/images/organization/jp/1.png",
  },
  {
    title: "Devanand Mahakud",
    subtitle: "Senior Instructor",
    imgUrl: "/images/organization/jp/2.png",
  },
  {
    title: "S V Sharan Raghavendra",
    subtitle: "Social Media Manager",
    imgUrl: "/images/organization/jp/3.png",
  },
  {
    title: "Mehul H Paleja",
    subtitle: "Marketing Head",
    imgUrl: "/images/organization/jp/4.png",
  },
  {
    title: "Kushal B",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/5.png",
  },
  {
    title: "Nagesh N",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/6.png",
  },
  {
    title: "Shelraz Balg",
    subtitle: "Senior Instructor",
    imgUrl: "/images/organization/jp/7.png",
  },
  {
    title: "Shri Varsha Suresh",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/8.png",
  },
  {
    title: "Madhusudan",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/9.png",
  },
  {
    title: "Aayush Manoj Tirmalle",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/10.png",
  },
  {
    title: "Tejash R",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/11.png",
  },
  {
    title: "Sanjana M",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/12.png",
  },
  {
    title: "Brunda M",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/13.png",
  },
  {
    title: "Shalini Menon",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/14.png",
  },
  {
    title: "S V Krithika",
    subtitle: "Instructor",
    imgUrl: "/images/organization/jp/15.png",
  },
  {
    title: "Nousheen P",
    subtitle: "Instructor",
    imgUrl: "/images/organization/jp/16.png",
  },
  {
    title: "Nikhil S",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/17.png",
  },
  {
    title: "Bhoomika Jingade A",
    subtitle: "Instructor",
    imgUrl: "/images/organization/jp/18.png",
  },
  {
    title: "Santosh",
    subtitle: "Instructor",
    imgUrl: "/images/organization/jp/19.png",
  },
  {
    title: "Syed Azhaan",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/20.png",
  },
  {
    title: "Nakshithra S",
    subtitle: "Referee",
    imgUrl: "/images/organization/jp/21.png",
  },
  {
    title: "Harish S",
    subtitle: "Judging Panel & Instructor",
    imgUrl: "/images/organization/jp/22.png",
  },
  {
    title: "Chandan K J",
    subtitle: "Judging Panel & Instructor",
    imgUrl: "/images/organization/jp/23.png",
  },
  {
    title: "Raghavendra",
    subtitle: "Judging Panel & Instructor",
    imgUrl: "/images/organization/jp/24.png",
  },
];

export const bbList = [
  "Aafiya Aimaan",
  "Aarav Goutham",
  "Aashrith Manoj Tirmalle",
  "Anagha R Naik",
  "Anirudh H",
  "Arun M S",
  "Atharva D",
  "Bhuvan",
  "Bhuvanesh",
  "Chandana P",
  "Darshin",
  "Deepika N",
  "Devanjana",
  "Elhaam Bint Shameem",
  "Gagan",
  "Gourinandhan",
  "Gunashree Seegehalli",
  "Harihar Subramaniam G",
  "HithaShree M",
  "Kushi",
  "Laya Rao M",
  "M S Shrisha",
  "Mariam Alia",
  "Meghana O R",
  "Mohammed Touseef",
  "Mugdha Goutham",
  "Nama Navid",
  "Nehal",
  "Noorain Zohna Sultana",
  "Prajin A",
  "Pranav",
  "Pruthvi",
  "Revanth Reddy Gajjala",
  "Saanvi",
  "Sachin Keerthan",
  "Samahith",
  "Sana",
  "Sanidhya G Acharya",
  "Sarah Fathima",
  "Shiv Kalbag",
  "Shreesha J P",
  "Shreesha S",
  "Shreyas R",
  "Sneha P",
  "Suraj Joshi",
  "Syed Ayaan",
  "Thanisha R",
  "Thazeen Saher Fathima",
  "Vinay Kumar D H",
  "Vyshnavi ",
  "Vyshnavi S",
  "Zaiba Quarth-Ul-Ain",
];
